### ISSUE TITLE
Cannot find module './lib/flatpath'

### ISSUE THREAD

**Issue by kunyan** [spaship/common#1]
The `lib/flatpath/index.js` has been renamed to `/lib/flatpath/flatpath` in npm package

it is the root cause of this error

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './lib/flatpath'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/kyan/sync-service/node_modules/@spaship/common/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by kunyan** [comment]
The issue is caused by `sync-service`'s `package-lock.json`.

Close this issue
